version: 0.2
env:
  variables:
    SNYK_TOKEN: "77b53117-a649-4d1c-a102-8e9fd3880fae"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo $SNYK_TOKEN
      - npm install -g snyk
      - npm install snyk-to-html -g
  pre_build:
    commands:
      - env
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - snyk test ||true --json > result-opensource.json
      - snyk monitor --all-projects --org=dfc53452-bd8c-4e29-90e0-a30d8055af24
      - snyk-to-html -o results.html -s
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  discard-paths: yes
